# This is a TOML document.

# newlines and trailing commas in inline tables
tbl = {
    key      = "a string",
    # comments
    moar-tbl =  {
        key = 1,
    },
}

# # \xHH notation
null = "null byte: \x00; letter a: \x61"

# # \e escape is 0x1B
csi = "\e["

# seconds in datetime and time are optional
dt = 2010-02-03 14:15
t  = 14:15
